spring:
  application:
    name: backtest-worker

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: when_authorized

server:
  port: ${SERVER_PORT:8085}
